
from datalab_sdk.api.exceptions import InputNotValid, ResourceNotFound

class ToolNotFound(ResourceNotFound):
    """Raised when the tool is not found by tool-inventory"""
    def __init__(self, tool_id: str, correlation_id: str = None):
        super().__init__(f"The requested tool ID {tool_id} was not found", correlation_id)

class ToolVersionNotFound(ResourceNotFound):
    """Raised when the specific tool version is not found by tool-inventory"""
    def __init__(self, tool_id: str, version_id: str, correlation_id: str = None):
        super().__init__(f"The requested tool ID {tool_id} version {version_id} was not found", correlation_id)

class ApprovedToolVersionNotFound(ResourceNotFound):
    """Raised when no approved version for the tool is found by tool-inventory"""
    def __init__(self, tool_id: str, correlation_id: str = None):
        super().__init__(f"No approved version for tool ID {tool_id} was found", correlation_id)
