from datalab_sdk.api.exceptions import InputNotValid, ResourceNotFound

class PlpNotFound(ResourceNotFound):
    """Raised when the requested info not found in plp"""
    def __init__(self, correlation_id: str = None):
        super().__init__(f"The requested info for plp not found", correlation_id)