
from datalab_sdk.api.exceptions import ResourceNotFound

class ModelNotFound(ResourceNotFound):
    """Raised when the specified model was not found by MME"""
    def __init__(self, model_id: str, correlation_id: str = None):
            super().__init__(f"The requested model ({model_id}) was not found in MME", correlation_id)

class ChainNotFound(ResourceNotFound):
    """Raised when the specified chain was not found by MME"""
    def __init__(self, chain_id: str, correlation_id: str = None):
            super().__init__(f"The requested chain ({chain_id}) was not found in MME", correlation_id)
