from datalab_sdk.api.exceptions import ResourceNotFound

class RecipeNotFound(ResourceNotFound):
    """Raised when the specified recipe was not found by PLM"""
    def __init__(self, recipe_key: str, correlation_id: str = None):
            super().__init__(f"The requested recipe ({recipe_key}) was not found in PLM", correlation_id)
