from datalab_sdk.api.exceptions import InputNotValid, ResourceNotFound

class DatabricksNotFound(ResourceNotFound):
    """Raised when the requested info not found in Databricks"""
    def __init__(self, correlation_id: str = None):
        super().__init__(f"The requested info for databricks not found", correlation_id)